steps:
  - label: ":docker: build image"
    key: image
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: docker
                image: crazymax/docker:latest
                command: [.buildkite/steps/image.sh]
  - label: "print image result"
    depends_on: image
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: busybox
                image: busybox:latest
                command:
                - buildkite-agent
                args:
                - meta-data
                - get
                - "image"
