steps:
  - label: ":docker: build image"
    key: image
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: docker
                image: crazymax/docker:latest
                command: [.buildkite/steps/image.sh]
                volumeMounts:
                - name: buildkit-client
                  mountPath: /buildkit/certs
            volumes:
            - name: buildkit-client
              secret:
                secretName: buildkit-client-certs
  - label: "print image result"
    depends_on: image
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: generic
                image: ubuntu:latest
                command:
                - buildkite-agent
                args:
                - meta-data
                - get
                - "image"
